In [9]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [21]:
import numpy as np
import polars as pl
from sweep.experiment import Experiment, ExperimentType
from model.data import DataModel, KFeaturesDefinition, k_features_factory
from erm.problems.problems import ProblemType
import subprocess
from experiments.data_loading import read_result_dataframe
import os
import matplotlib.pyplot as plt
import datetime
from experiments.data_loading import KEYS
from matplotlib.lines import Line2D

Define a datamodel

In [11]:
d = 100

In [12]:
vanilla_gaussian_kwargs = {
    "x_diagonal": KFeaturesDefinition(diagonal=[(1, d)]),
    "θ_diagonal": KFeaturesDefinition(diagonal=[(1, d)]),
    "ω_diagonal": KFeaturesDefinition(diagonal=[(1, d)]),
    "δ_diagonal": KFeaturesDefinition(diagonal=[(1, d)]),
    "ν_diagonal": KFeaturesDefinition(diagonal=[(1, d)]),
}

vanilla_datamodel = DataModel(
    d,
    normalize_matrices=True,
    data_model_factory=k_features_factory,
    factory_kwargs=vanilla_gaussian_kwargs,
    name="vanilla-gaussian"
)

Define an experiment

In [66]:
experiment = Experiment(
    state_evolution_repetitions=1,
    erm_repetitions=1,
    alphas=np.logspace(-0.2,2,3),
    epsilons=np.array([0.0, 0.1, 0.2, 0.3]),
    lambdas=np.array([0.001]),
    taus=np.array([0.05]),
    d=d,
    experiment_type=ExperimentType.Sweep,
    data_models = [vanilla_datamodel],
    test_against_epsilons=np.array([0.2]),
    erm_problem_type=ProblemType.PerturbedLogistic,
    gamma_fair_error=0.01,
    name="perturbed_logistic"
)
experiment_json = experiment.to_json()

In [14]:
with open("perturbed_logistic.json", "w") as f:
    f.write(experiment_json)

In [15]:
venv_python = ".venv/bin/python"
command = ["mpiexec", "-n", "5", venv_python, "sweep/run_sweep.py", "--json", experiment_json, "--log-level", "INFO"]
subprocess.run(command)

2025-02-27 22:10:14,240 - Rank 0 - INFO - The MPI comm size is 5
2025-02-27 22:10:14,240 - Rank 0 - INFO - This process has rank 0
2025-02-27 22:10:14,240 - Rank 0 - INFO - Starting Master for experiment perturbed_logistic
2025-02-27 22:10:14,241 - Rank 0 - INFO - Starting Experiment perturbed_logistic
2025-02-27 22:10:14,255 - Rank 0 - INFO - Starting all processes
2025-02-27 22:10:14,256 - Rank 0 - INFO - Sending task 0 to 1
2025-02-27 22:10:14,257 - Rank 0 - INFO - Sending task 1 to 2
2025-02-27 22:10:14,257 - Rank 0 - INFO - Sending task 2 to 3
2025-02-27 22:10:14,257 - Rank 0 - INFO - Sending task 3 to 4
2025-02-27 22:10:14,257 - Rank 0 - INFO - All processes started - receiving results and sending new tasks
2025-02-27 22:10:14,257 - Rank 0 - INFO - Received the 0th task


INFO:root:The MPI comm size is 5
INFO:root:This process has rank 0
INFO:root:Starting Master for experiment perturbed_logistic
INFO:root:Starting Experiment perturbed_logistic
INFO:root:The MPI comm size is 5
INFO:root:The MPI comm size is 5
INFO:root:The MPI comm size is 5
INFO:root:The MPI comm size is 5
INFO:root:This process has rank 3
INFO:root:This process has rank 2
INFO:root:This process has rank 4
INFO:root:This process has rank 1
  0%|          | 0/24 [00:00<?, ?it/s]INFO:root:Starting all processes
INFO:root:Sending task 0 to 1
INFO:root:Sending task 1 to 2
INFO:root:Sending task 2 to 3
INFO:root:Sending task 3 to 4
INFO:root:All processes started - receiving results and sending new tasks
INFO:root:Starting task 2
INFO:root:Starting task 1
INFO:root:Initializing data model
INFO:root:Initializing data model
INFO:root:Starting task 4
INFO:root:Initializing data model
INFO:root:Received the 0th task
INFO:root:Starting task 3
INFO:root:Initializing data model
INFO:root:d: 100
IN

2025-02-27 22:10:15,528 - Rank 0 - INFO - Received task 1 from 1
2025-02-27 22:10:15,528 - Rank 0 - INFO - Saved Task(id=1, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=0.6309573444801932, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x157bd5950>)
2025-02-27 22:10:15,528 - Rank 0 - INFO - Received the 1th task
2025-02-27 22:10:15,637 - Rank 0 - INFO - Received task 2 from 2
2025-02-27 22:10:15,637 - Rank 0 - INFO - Save

INFO:root:Received task 4 from 4
INFO:root:Saved Task(id=4, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=0.6309573444801932, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x157bd6a90>)
INFO:root:Received the 4th task
INFO:root:Starting task 8
INFO:root:Initializing data model
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO

2025-02-27 22:10:16,881 - Rank 0 - INFO - Received task 5 from 1
2025-02-27 22:10:16,881 - Rank 0 - INFO - Saved Task(id=5, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.943282347242818, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x157bd7150>)
2025-02-27 22:10:16,881 - Rank 0 - INFO - Received the 5th task


INFO:root:Finished State Evolution Task(id=8, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.943282347242818, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=None)
INFO:root:Received task 8 from 4
INFO:root:Saved Task(id=8, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.943282347242818, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs

2025-02-27 22:10:17,109 - Rank 0 - INFO - Received task 8 from 4
2025-02-27 22:10:17,109 - Rank 0 - INFO - Saved Task(id=8, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.943282347242818, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x157bd7550>)
2025-02-27 22:10:17,109 - Rank 0 - INFO - Received the 6th task


INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_δ: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ν: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_x value counts: (array([0., 1.]), array([9900,  100]))
IN

2025-02-27 22:10:18,411 - Rank 0 - INFO - Received task 7 from 3
2025-02-27 22:10:18,411 - Rank 0 - INFO - Saved Task(id=7, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.943282347242818, epsilon=0.2, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x157bd7bd0>)
2025-02-27 22:10:18,411 - Rank 0 - INFO - Received the 7th task


INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_δ: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ν: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_x value counts: (array([0., 1.]), array([9900,  100]))
IN

2025-02-27 22:10:19,680 - Rank 0 - INFO - Received task 6 from 2
2025-02-27 22:10:19,680 - Rank 0 - INFO - Saved Task(id=6, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.943282347242818, epsilon=0.1, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x157bd6f50>)
2025-02-27 22:10:19,681 - Rank 0 - INFO - Received the 8th task


INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_δ: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ν: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_x value counts: (array([0., 1.]), array([9900,  100]))
IN

2025-02-27 22:10:20,552 - Rank 0 - INFO - Received task 11 from 3
2025-02-27 22:10:20,552 - Rank 0 - INFO - Saved Task(id=11, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=100.0, epsilon=0.2, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x157be0790>)
2025-02-27 22:10:20,552 - Rank 0 - INFO - Received the 9th task


INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_δ: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ν: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_x value counts: (array([0., 1.]), array([9900,  100]))
IN

2025-02-27 22:10:21,317 - Rank 0 - INFO - Received task 12 from 2
2025-02-27 22:10:21,317 - Rank 0 - INFO - Saved Task(id=12, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=100.0, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x157be0a90>)
2025-02-27 22:10:21,321 - Rank 0 - INFO - Received the 10th task


INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:iter_nb: 1000, err: 0.09323999060256938
INFO:root:error: 0.09323999060256938
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0

2025-02-27 22:10:22,980 - Rank 0 - INFO - Received task 13 from 3
2025-02-27 22:10:22,980 - Rank 0 - INFO - Saved Task(id=13, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=0.6309573444801932, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x157be0dd0>)
2025-02-27 22:10:22,980 - Rank 0 - INFO - Received the 11th task


INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:Finished State Evolution Task(id=10, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=100.0, epsilon=0.1, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=None)
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:Received task 10 from 4
INFO:root:Saved Task(id=10, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=100.0, epsilon=0.1, t

2025-02-27 22:10:23,426 - Rank 0 - INFO - Received task 10 from 4
2025-02-27 22:10:23,427 - Rank 0 - INFO - Saved Task(id=10, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=100.0, epsilon=0.1, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x157be1250>)
2025-02-27 22:10:23,427 - Rank 0 - INFO - Received the 12th task


INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_δ: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ν: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.

2025-02-27 22:10:24,095 - Rank 0 - INFO - Received task 14 from 2
2025-02-27 22:10:24,095 - Rank 0 - INFO - Saved Task(id=14, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=0.6309573444801932, epsilon=0.1, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x157be17d0>)
2025-02-27 22:10:24,095 - Rank 0 - INFO - Received the 13th task


INFO:root:{'lambda_twiddle_1': 0.49290362157709555, 'lambda_twiddle_2': 0.0018000000000000004}
INFO:root:{'lambda_twiddle_1': 0.2060621459948111, 'lambda_twiddle_2': 0.0008500000000000002}
INFO:root:{'lambda_twiddle_1': 0.02020545650434725, 'lambda_twiddle_2': 0.00010000000000000002}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0

2025-02-27 22:10:25,890 - Rank 0 - INFO - Received task 15 from 3
2025-02-27 22:10:25,890 - Rank 0 - INFO - Saved Task(id=15, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=0.6309573444801932, epsilon=0.2, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x157be1b90>)
2025-02-27 22:10:25,890 - Rank 0 - INFO - Received the 14th task


INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0.

2025-02-27 22:10:26,539 - Rank 0 - INFO - Received task 16 from 4
2025-02-27 22:10:26,539 - Rank 0 - INFO - Saved Task(id=16, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=0.6309573444801932, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x157be1c10>)
2025-02-27 22:10:26,541 - Rank 0 - INFO - Received the 15th task


INFO:root:{'lambda_twiddle_1': 2.542060871718453, 'lambda_twiddle_2': 0.004712500000000001}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 1.6726335604398312, 'lambda_twiddle_2': 0.0034375000000000005}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.30855756632401893, 'lambda_twiddle_2': 0.0007250000000000001}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.2597664494340783, 'lambda_twiddle_2': 0.0006250000000000001}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0

2025-02-27 22:10:29,327 - Rank 0 - INFO - Received task 17 from 2
2025-02-27 22:10:29,327 - Rank 0 - INFO - Saved Task(id=17, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=7.943282347242818, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x157be2450>)
2025-02-27 22:10:29,327 - Rank 0 - INFO - Received the 16th task


INFO:root:{'lambda_twiddle_1': 0.015316897975045159, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.42318629118613893, 'lambda_twiddle_2': 0.0044}
INFO:root:{'lambda_twiddle_1': 0.015319433810538803, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.42319039749751874, 'lambda_twiddle_2': 0.0044}
INFO:root:{'lambda_twiddle_1': 0.015326736033444664, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.42319673476023045, 'lambda_twiddle_2': 0.0044}
INFO:root:{'lambda_twiddle_1': 0.015329088381636189, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.015329279933999782, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.4232119714429027, 'lambda_twiddle_2': 0.0044}
INFO:root:{'lambda_twiddle_1': 0.01532724622645593, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.015326513482888184, 'lambda_twiddle_2': 0.00011250000000000002}
INF

2025-02-27 22:10:30,246 - Rank 0 - INFO - Received task 19 from 4
2025-02-27 22:10:30,247 - Rank 0 - INFO - Saved Task(id=19, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=7.943282347242818, epsilon=0.2, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x157be28d0>)
2025-02-27 22:10:30,253 - Rank 0 - INFO - Received the 17th task


INFO:root:{'lambda_twiddle_1': 9.46663496764791, 'lambda_twiddle_2': 0.052762500000000004}
INFO:root:{'lambda_twiddle_1': 8.86487965779537, 'lambda_twiddle_2': 0.05085}
INFO:root:iter_nb: 2000, err: 0.0018544444885719713
INFO:root:error: 0.0018544444885719713
INFO:root:{'lambda_twiddle_1': 6.434899967975296, 'lambda_twiddle_2': 0.0414}
INFO:root:Finished ERM Task(id=18, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=7.943282347242818, epsilon=0.1, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={},

2025-02-27 22:10:30,779 - Rank 0 - INFO - Received task 18 from 3
2025-02-27 22:10:30,779 - Rank 0 - INFO - Saved Task(id=18, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=7.943282347242818, epsilon=0.1, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x157be2950>)
2025-02-27 22:10:30,779 - Rank 0 - INFO - Received the 18th task


INFO:root:{'lambda_twiddle_1': 1.5342803850768019, 'lambda_twiddle_2': 0.0144}
INFO:root:{'lambda_twiddle_1': 1.302642756901383, 'lambda_twiddle_2': 0.0138375}
INFO:root:{'lambda_twiddle_1': 1.1936266876136366, 'lambda_twiddle_2': 0.013387499999999998}
INFO:root:{'lambda_twiddle_1': 1.1279612596754385, 'lambda_twiddle_2': 0.013725000000000001}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:{'lambda_twiddle_1': 1.056152860053725, 'lambda_twiddle_2': 0.013387499999999998}
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]

2025-02-27 22:10:32,519 - Rank 0 - INFO - Received task 20 from 2
2025-02-27 22:10:32,519 - Rank 0 - INFO - Saved Task(id=20, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=7.943282347242818, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x157be3190>)
2025-02-27 22:10:32,519 - Rank 0 - INFO - Received the 19th task


INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 4.759034976948531, 'lambda_twiddle_2': 0.011425000000000003}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 3.4695612238589577, 'lambda_twiddle_2': 0.009512500000000002}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 3.188506455652166, 'lambda_twiddle_2': 0.009287500000000002}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 3.1007054230794875, 'lambda_twiddle_2': 0.009425000000000003}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1

2025-02-27 22:10:34,993 - Rank 0 - INFO - Received task 22 from 3
2025-02-27 22:10:34,993 - Rank 0 - INFO - Saved Task(id=22, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=100.0, epsilon=0.1, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x157be3450>)
2025-02-27 22:10:34,993 - Rank 0 - INFO - Received the 20th task


INFO:root:{'lambda_twiddle_1': 10.26581485980699, 'lambda_twiddle_2': 0.07695000000000002}
INFO:root:Finished ERM Task(id=21, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=100.0, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=None)
INFO:root:Received task 21 from 4
INFO:root:Saved Task(id=21, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=100.0, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau

2025-02-27 22:10:35,276 - Rank 0 - INFO - Received task 21 from 4
2025-02-27 22:10:35,282 - Rank 0 - INFO - Saved Task(id=21, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=100.0, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x157be3650>)
2025-02-27 22:10:35,311 - Rank 0 - INFO - Received the 21th task


INFO:root:{'lambda_twiddle_1': 10.45292526508915, 'lambda_twiddle_2': 0.07640000000000001}
INFO:root:{'lambda_twiddle_1': 10.192414922439008, 'lambda_twiddle_2': 0.07635000000000002}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_δ: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ν: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0.

2025-02-27 22:10:36,674 - Rank 0 - INFO - Received task 23 from 2
2025-02-27 22:10:36,674 - Rank 0 - INFO - Saved Task(id=23, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=100.0, epsilon=0.2, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x157bf8710>)
2025-02-27 22:10:36,674 - Rank 0 - INFO - Received the 22th task


INFO:root:{'lambda_twiddle_1': 26.12741237862273, 'lambda_twiddle_2': 0.2649375}
INFO:root:{'lambda_twiddle_1': 25.415645376241795, 'lambda_twiddle_2': 0.26415}
INFO:root:{'lambda_twiddle_1': 24.957781721437875, 'lambda_twiddle_2': 0.2638125}
INFO:root:{'lambda_twiddle_1': 24.792868855380526, 'lambda_twiddle_2': 0.264825}
INFO:root:{'lambda_twiddle_1': 24.741878149583165, 'lambda_twiddle_2': 0.264375}
INFO:root:{'lambda_twiddle_1': 24.773208207540478, 'lambda_twiddle_2': 0.2644875}
INFO:root:{'lambda_twiddle_1': 24.77392814551851, 'lambda_twiddle_2': 0.2644875}
INFO:root:{'lambda_twiddle_1': 24.773867841429688, 'lambda_twiddle_2': 0.2644875}
INFO:root:Finished ERM Task(id=24, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=100.0, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal

2025-02-27 22:10:37,684 - Rank 0 - INFO - Received task 24 from 3
2025-02-27 22:10:37,684 - Rank 0 - INFO - Saved Task(id=24, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.PerturbedLogistic: 1>, alpha=100.0, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x157be0850>)
2025-02-27 22:10:37,684 - Rank 0 - INFO - Received the 23th task


INFO:root:iter_nb: 3000, err: 3.658623472801992e-05
INFO:root:error: 3.658623472801992e-05
INFO:root:Finished State Evolution Task(id=9, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=100.0, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=None)
INFO:root:Received task 9 from 1
INFO:root:Saved Task(id=9, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=100.0, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_m

2025-02-27 22:10:38,804 - Rank 0 - INFO - Received task 9 from 1
2025-02-27 22:10:38,804 - Rank 0 - INFO - Saved Task(id=9, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=100.0, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x157bf8810>)
2025-02-27 22:10:38,804 - Rank 0 - INFO - All tasks sent and received
2025-02-27 22:10:38,808 - Rank 0 - INFO - Marking experiment perturbed_logistic as finished
2025-02-27 22:10:38,808 - 

CompletedProcess(args=['mpiexec', '-n', '5', '.venv/bin/python', 'sweep/run_sweep.py', '--json', '{"name": "perturbed_logistic", "state_evolution_repetitions": 1, "erm_repetitions": 1, "alphas": [0.6309573444801932, 7.943282347242818, 100.0], "epsilons": [0.0, 0.1, 0.2, 0.3], "test_against_epsilons": [0.2], "lambdas": [0.001], "taus": [0.05], "d": 100, "experiment_type": "Sweep", "data_models": [{"d": 100, "normalize_matrices": true, "data_model_factory_name": "k_features_factory", "factory_kwargs": {"x_diagonal": {"diagonal": [[1, 100]]}, "\\u03b8_diagonal": {"diagonal": [[1, 100]]}, "\\u03c9_diagonal": {"diagonal": [[1, 100]]}, "\\u03b4_diagonal": {"diagonal": [[1, 100]]}, "\\u03bd_diagonal": {"diagonal": [[1, 100]]}}, "name": "vanilla-gaussian", "description": "", "gamma": 1}], "erm_problem_type": "PerturbedLogistic", "gamma_fair_error": 0.01}', '--log-level', 'INFO'], returncode=0)

In [16]:
df = read_result_dataframe(experiment.name)

/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/experiments/data_loading.py:50: UserWarning: `to_struct()` should be passed a list of field names to avoid query errors in subsequent operations (e.g. <struct operation> not supported for dtype Unknown)
  df.with_columns(pl.col(column_list[i]).list.to_struct())


In [50]:
key_value_dict = {
    tuple(row[k] for k in KEYS if "epsilon_g" != k): {col: row[col] for col in ["lambda_twiddle_1","lambda_twiddle_2"]} 
    for row in df.to_dicts()
}

In [67]:
experiment.name = "coefficient-logistic"
experiment.erm_problem_type = ProblemType.CoefficientLogistic
experiment.values_map = key_value_dict

In [68]:
experiment_json = experiment.to_json()

In [71]:
with open("coefficient_logistic.json", "w") as f:
    f.write(experiment_json)

In [74]:

venv_python = ".venv/bin/python"
command = ["mpiexec", "-n", "5", venv_python, "sweep/run_sweep.py", "--json", experiment_json, "--log-level", "INFO"]
subprocess.run(command)

2025-02-27 22:51:37,674 - Rank 0 - INFO - The MPI comm size is 5
2025-02-27 22:51:37,674 - Rank 0 - INFO - This process has rank 0
2025-02-27 22:51:37,674 - Rank 0 - INFO - Starting Master for experiment coefficient-logistic
2025-02-27 22:51:37,674 - Rank 0 - INFO - Starting Experiment coefficient-logistic
2025-02-27 22:51:37,690 - Rank 0 - INFO - Starting all processes
2025-02-27 22:51:37,690 - Rank 0 - INFO - Sending task 0 to 1
2025-02-27 22:51:37,690 - Rank 0 - INFO - Sending task 1 to 2
2025-02-27 22:51:37,690 - Rank 0 - INFO - Sending task 2 to 3
2025-02-27 22:51:37,690 - Rank 0 - INFO - Sending task 3 to 4
2025-02-27 22:51:37,690 - Rank 0 - INFO - All processes started - receiving results and sending new tasks
2025-02-27 22:51:37,692 - Rank 0 - INFO - Received the 0th task


INFO:root:The MPI comm size is 5
INFO:root:This process has rank 0
INFO:root:Starting Master for experiment coefficient-logistic
INFO:root:Starting Experiment coefficient-logistic
INFO:root:The MPI comm size is 5
INFO:root:The MPI comm size is 5
INFO:root:The MPI comm size is 5
INFO:root:This process has rank 1
INFO:root:The MPI comm size is 5
INFO:root:This process has rank 4
INFO:root:This process has rank 2
INFO:root:This process has rank 3
  0%|          | 0/24 [00:00<?, ?it/s]INFO:root:Starting all processes
INFO:root:Sending task 0 to 1
INFO:root:Sending task 1 to 2
INFO:root:Sending task 2 to 3
INFO:root:Sending task 3 to 4
INFO:root:Starting task 1
INFO:root:Initializing data model
INFO:root:Starting task 2
INFO:root:Initializing data model
INFO:root:Starting task 3
INFO:root:Initializing data model
INFO:root:Starting task 4
INFO:root:All processes started - receiving results and sending new tasks
INFO:root:Received the 0th task
INFO:root:Initializing data model
INFO:root:d: 10

2025-02-27 22:51:39,964 - Rank 0 - INFO - Received task 1 from 1
2025-02-27 22:51:39,964 - Rank 0 - INFO - Saved Task(id=1, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=0.6309573444801932, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values=None, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x1688d9710>)
2025-02-27 22:51:39,964 - Rank 0 - INFO - Received the 1th task
2025-02-27 22:51:39,969 - Rank 0 - INFO - Received task 3 from 3
2025-02-27 22:51:39,969 - Rank 0 - INFO - Sa

INFO:root:Starting task 8
INFO:root:Initializing data model
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_δ: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ν: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root

2025-02-27 22:51:41,639 - Rank 0 - INFO - Received task 5 from 1
2025-02-27 22:51:41,639 - Rank 0 - INFO - Saved Task(id=5, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.943282347242818, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values=None, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x1688daed0>)
2025-02-27 22:51:41,639 - Rank 0 - INFO - Received the 5th task
2025-02-27 22:51:41,772 - Rank 0 - INFO - Received task 8 from 4
2025-02-27 22:51:41,772 - Rank 0 - INFO - Sav

INFO:root:Finished State Evolution Task(id=7, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.943282347242818, epsilon=0.2, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values=None, gamma_fair_error=0.01, gamma=1, result=None)
INFO:root:Received task 7 from 2
INFO:root:Saved Task(id=7, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.943282347242818, epsilon=0.2, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwar

2025-02-27 22:51:42,684 - Rank 0 - INFO - Received task 7 from 2
2025-02-27 22:51:42,684 - Rank 0 - INFO - Saved Task(id=7, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.943282347242818, epsilon=0.2, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values=None, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x1688db6d0>)
2025-02-27 22:51:42,684 - Rank 0 - INFO - Received the 7th task


INFO:root:iter_nb: 500, err: 0.6302174513317595
INFO:root:error: 0.6302174513317595
INFO:root:iter_nb: 500, err: 0.006413947502210249
INFO:root:error: 0.006413947502210249
INFO:root:Finished State Evolution Task(id=6, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.943282347242818, epsilon=0.1, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values=None, gamma_fair_error=0.01, gamma=1, result=None)
INFO:root:Received task 6 from 3
INFO:root:Saved Task(id=6, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.943282347242818, ep

2025-02-27 22:51:43,637 - Rank 0 - INFO - Received task 6 from 3
2025-02-27 22:51:43,637 - Rank 0 - INFO - Saved Task(id=6, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.943282347242818, epsilon=0.1, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values=None, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x1688dbbd0>)
2025-02-27 22:51:43,637 - Rank 0 - INFO - Received the 8th task


INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_δ: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ν: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_x value counts: (array([0., 1.]), array([9900,  100]))
IN

2025-02-27 22:51:44,333 - Rank 0 - INFO - Received task 11 from 2
2025-02-27 22:51:44,333 - Rank 0 - INFO - Saved Task(id=11, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=100.0, epsilon=0.2, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values=None, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x1688db5d0>)
2025-02-27 22:51:44,333 - Rank 0 - INFO - Received the 9th task


INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:Finished State Evolution Task(id=12, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=100.0, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]),

2025-02-27 22:51:44,891 - Rank 0 - INFO - Received task 12 from 3
2025-02-27 22:51:44,891 - Rank 0 - INFO - Saved Task(id=12, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=100.0, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values=None, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x1688d0910>)
2025-02-27 22:51:44,891 - Rank 0 - INFO - Received the 10th task


INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:d: 100
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0.

2025-02-27 22:51:46,178 - Rank 0 - INFO - Received task 13 from 2
2025-02-27 22:51:46,178 - Rank 0 - INFO - Saved Task(id=13, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=0.6309573444801932, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x1688d8a90>)
2025-02-27 22:51:46,178 - Rank 0 - INFO - Received the 11th task


INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_δ: [[1. 0. 0. ... 0. 0. 0.]
 [0. 

2025-02-27 22:51:47,293 - Rank 0 - INFO - Received task 14 from 3
2025-02-27 22:51:47,293 - Rank 0 - INFO - Saved Task(id=14, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=0.6309573444801932, epsilon=0.1, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x1688f0850>)
2025-02-27 22:51:47,293 - Rank 0 - INFO - Received the 12th task
2025-02-27 22:51:47,436 - Rank 0 - INF

INFO:root:Starting task 17
INFO:root:Initializing data model
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0.

2025-02-27 22:51:49,556 - Rank 0 - INFO - Received task 15 from 2
2025-02-27 22:51:49,560 - Rank 0 - INFO - Saved Task(id=15, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=0.6309573444801932, epsilon=0.2, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x1688f1510>)
2025-02-27 22:51:49,560 - Rank 0 - INFO - Received the 14th task


INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.

2025-02-27 22:51:51,812 - Rank 0 - INFO - Received task 16 from 3
2025-02-27 22:51:51,812 - Rank 0 - INFO - Saved Task(id=16, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=0.6309573444801932, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x1688f12d0>)
2025-02-27 22:51:51,818 - Rank 0 - INFO - Received the 15th task


INFO:root:{'lambda_twiddle_1': 0.015324293023336495, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.015324293023336495, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.015324293023336495, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.015324293023336495, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 0.015324293023336495, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm 

2025-02-27 22:51:55,110 - Rank 0 - INFO - Received task 17 from 4
2025-02-27 22:51:55,110 - Rank 0 - INFO - Saved Task(id=17, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=7.943282347242818, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x1688f1650>)
2025-02-27 22:51:55,110 - Rank 0 - INFO - Received the 16th task


INFO:root:{'lambda_twiddle_1': 0.015324293023336495, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.4232119714429027, 'lambda_twiddle_2': 0.0044}
INFO:root:{'lambda_twiddle_1': 0.015324293023336495, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.4232119714429027, 'lambda_twiddle_2': 0.0044}
INFO:root:{'lambda_twiddle_1': 0.015324293023336495, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.4232119714429027, 'lambda_twiddle_2': 0.0044}
INFO:root:{'lambda_twiddle_1': 0.015324293023336495, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.4232119714429027, 'lambda_twiddle_2': 0.0044}
INFO:root:{'lambda_twiddle_1': 0.015324293023336495, 'lambda_twiddle_2': 0.00011250000000000002}
INFO:root:{'lambda_twiddle_1': 0.4232119714429027, 'lambda_twiddle_2': 0.0044}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last 

2025-02-27 22:51:56,574 - Rank 0 - INFO - Received task 18 from 2
2025-02-27 22:51:56,574 - Rank 0 - INFO - Saved Task(id=18, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=7.943282347242818, epsilon=0.1, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={'lambda_twiddle_1': 0.015324293023336495, 'lambda_twiddle_2': 0.00011250000000000002}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x1688d1b90>)
2025-02-27 22:51:56,574 - Rank 0 - INFO - Received the 17th task


INFO:root:{'lambda_twiddle_1': 1.0492545948419525, 'lambda_twiddle_2': 0.013387499999999998}
INFO:root:{'lambda_twiddle_1': 0.4232119714429027, 'lambda_twiddle_2': 0.0044}
INFO:root:{'lambda_twiddle_1': 1.0492545948419525, 'lambda_twiddle_2': 0.013387499999999998}
INFO:root:{'lambda_twiddle_1': 1.0492545948419525, 'lambda_twiddle_2': 0.013387499999999998}
INFO:root:{'lambda_twiddle_1': 1.0492545948419525, 'lambda_twiddle_2': 0.013387499999999998}
INFO:root:{'lambda_twiddle_1': 1.0492545948419525, 'lambda_twiddle_2': 0.013387499999999998}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.

2025-02-27 22:51:57,609 - Rank 0 - INFO - Received task 19 from 3
2025-02-27 22:51:57,609 - Rank 0 - INFO - Saved Task(id=19, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=7.943282347242818, epsilon=0.2, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={'lambda_twiddle_1': 0.4232119714429027, 'lambda_twiddle_2': 0.0044}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x1688d9f10>)
2025-02-27 22:51:57,609 - Rank 0 - INFO - Received the 18th task


INFO:root:{'lambda_twiddle_1': 1.0492545948419525, 'lambda_twiddle_2': 0.013387499999999998}
INFO:root:{'lambda_twiddle_1': 1.0492545948419525, 'lambda_twiddle_2': 0.013387499999999998}
INFO:root:{'lambda_twiddle_1': 1.0492545948419525, 'lambda_twiddle_2': 0.013387499999999998}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:iter_nb: 2500, err: 0.0002604907913337229
INFO:root:error: 0.0002604907913337229
INFO:root:{'lambda_twiddle_1': 1.0492545948419525, 'lambda_twiddle_2': 0.013387499999999998}
INFO:root:{'lambda_twiddle_1': 1.0492545948419525, 'lambda_twiddle_2': 0.013387499999999998}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1.

2025-02-27 22:51:59,569 - Rank 0 - INFO - Received task 20 from 4
2025-02-27 22:51:59,569 - Rank 0 - INFO - Saved Task(id=20, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=7.943282347242818, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={'lambda_twiddle_1': 1.0492545948419525, 'lambda_twiddle_2': 0.013387499999999998}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x1688da310>)
2025-02-27 22:51:59,569 - Rank 0 - INFO - Received the 19th task


INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 2.782774556932757, 'lambda_twiddle_2': 0.009337500000000002}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 2.782774556932757, 'lambda_twiddle_2': 0.009337500000000002}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 2.782774556932757, 'lambda_twiddle_2': 0.009337500000000002}
INFO:root:{'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}
INFO:root:{'lambda_twiddle_1': 2.782774556932757, 'lambda_twiddle_2': 0.009337500000000002}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 

2025-02-27 22:52:02,836 - Rank 0 - INFO - Received task 22 from 3
2025-02-27 22:52:02,836 - Rank 0 - INFO - Saved Task(id=22, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=100.0, epsilon=0.1, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={'lambda_twiddle_1': 2.782774556932757, 'lambda_twiddle_2': 0.009337500000000002}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x1688f2110>)
2025-02-27 22:52:02,836 - Rank 0 - INFO - Received the 20th task


INFO:root:{'lambda_twiddle_1': 10.10103856296431, 'lambda_twiddle_2': 0.07605}
INFO:root:Finished ERM Task(id=21, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=100.0, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}, gamma_fair_error=0.01, gamma=1, result=None)
INFO:root:Received task 21 from 2
INFO:root:Saved Task(id=21, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=100.0, epsilon=0.0, tes

2025-02-27 22:52:03,216 - Rank 0 - INFO - Received task 21 from 2
2025-02-27 22:52:03,217 - Rank 0 - INFO - Saved Task(id=21, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=100.0, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={'lambda_twiddle_1': 0.0, 'lambda_twiddle_2': 0.0}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x1688daa90>)
2025-02-27 22:52:03,217 - Rank 0 - INFO - Received the 21th task


INFO:root:{'lambda_twiddle_1': 10.10103856296431, 'lambda_twiddle_2': 0.07605}
INFO:root:d: 100
INFO:root:normalize_matrices: True
INFO:root:Normalizing the matrices
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_δ: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ν: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0

2025-02-27 22:52:04,093 - Rank 0 - INFO - Received task 23 from 4
2025-02-27 22:52:04,093 - Rank 0 - INFO - Saved Task(id=23, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=100.0, epsilon=0.2, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={'lambda_twiddle_1': 10.10103856296431, 'lambda_twiddle_2': 0.07605}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x1688f3810>)
2025-02-27 22:52:04,093 - Rank 0 - INFO - Received the 22th task


INFO:root:{'lambda_twiddle_1': 24.773867841429688, 'lambda_twiddle_2': 0.2644875}
INFO:root:{'lambda_twiddle_1': 24.773867841429688, 'lambda_twiddle_2': 0.2644875}
INFO:root:{'lambda_twiddle_1': 24.773867841429688, 'lambda_twiddle_2': 0.2644875}
INFO:root:{'lambda_twiddle_1': 24.773867841429688, 'lambda_twiddle_2': 0.2644875}
INFO:root:{'lambda_twiddle_1': 24.773867841429688, 'lambda_twiddle_2': 0.2644875}
INFO:root:Finished State Evolution Task(id=9, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=100.0, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussia

2025-02-27 22:52:04,644 - Rank 0 - INFO - Received task 9 from 1
2025-02-27 22:52:04,645 - Rank 0 - INFO - Saved Task(id=9, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=100.0, epsilon=0.0, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values=None, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x1688f3ad0>)
2025-02-27 22:52:04,645 - Rank 0 - INFO - Received the 23th task


INFO:root:{'lambda_twiddle_1': 24.773867841429688, 'lambda_twiddle_2': 0.2644875}
INFO:root:{'lambda_twiddle_1': 24.773867841429688, 'lambda_twiddle_2': 0.2644875}
INFO:root:{'lambda_twiddle_1': 24.773867841429688, 'lambda_twiddle_2': 0.2644875}
INFO:root:{'lambda_twiddle_1': 24.773867841429688, 'lambda_twiddle_2': 0.2644875}
INFO:root:{'lambda_twiddle_1': 24.773867841429688, 'lambda_twiddle_2': 0.2644875}
INFO:root:{'lambda_twiddle_1': 24.773867841429688, 'lambda_twiddle_2': 0.2644875}
INFO:root:Finished ERM Task(id=24, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=100.0, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinit

2025-02-27 22:52:05,489 - Rank 0 - INFO - Received task 24 from 3
2025-02-27 22:52:05,489 - Rank 0 - INFO - Saved Task(id=24, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.CoefficientLogistic: 2>, alpha=100.0, epsilon=0.3, test_against_epsilons=[0.2], lam=0.001, tau=0.05, d=100, data_model=DataModel(d=100, normalize_matrices=True, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='vanilla-gaussian', description='', gamma=1), values={'lambda_twiddle_1': 24.773867841429688, 'lambda_twiddle_2': 0.2644875}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.erm.ERMResult object at 0x1688f3e90>)
2025-02-27 22:52:05,489 - Rank 0 - INFO - All tasks sent and received
2025-02-27 22:52:05,497 -

CompletedProcess(args=['mpiexec', '-n', '5', '.venv/bin/python', 'sweep/run_sweep.py', '--json', '{"name": "coefficient-logistic", "state_evolution_repetitions": 1, "erm_repetitions": 1, "alphas": [0.6309573444801932, 7.943282347242818, 100.0], "epsilons": [0.0, 0.1, 0.2, 0.3], "test_against_epsilons": [0.2], "lambdas": [0.001], "taus": [0.05], "d": 100, "experiment_type": "Sweep", "data_models": [{"d": 100, "normalize_matrices": true, "data_model_factory_name": "k_features_factory", "factory_kwargs": {"x_diagonal": {"diagonal": [[1, 100]]}, "\\u03b8_diagonal": {"diagonal": [[1, 100]]}, "\\u03c9_diagonal": {"diagonal": [[1, 100]]}, "\\u03b4_diagonal": {"diagonal": [[1, 100]]}, "\\u03bd_diagonal": {"diagonal": [[1, 100]]}}, "name": "vanilla-gaussian", "description": "", "gamma": 1}], "erm_problem_type": "CoefficientLogistic", "gamma_fair_error": 0.01, "values_map": {"(7.943282347242818, 0.3, 0.05, 0.001, \'vanilla-gaussian\')": {"lambda_twiddle_1": 1.0492545948419525, "lambda_twiddle_2"

In [75]:
df2 = read_result_dataframe("coefficient-logistic")

/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/experiments/data_loading.py:50: UserWarning: `to_struct()` should be passed a list of field names to avoid query errors in subsequent operations (e.g. <struct operation> not supported for dtype Unknown)
  df.with_columns(pl.col(column_list[i]).list.to_struct())


In [76]:
df2

shape: (12, 148)
┌──────────┬─────────┬──────┬───────┬───┬──────────────┬──────────────┬──────────────┬─────────────┐
│ alpha    ┆ epsilon ┆ tau  ┆ lam   ┆ … ┆ boundary_los ┆ training_los ┆ test_losses_ ┆ duration_st │
│ ---      ┆ ---     ┆ ---  ┆ ---   ┆   ┆ s_test_es_st ┆ s_std_erm    ┆ std_erm      ┆ d_erm       │
│ f64      ┆ f64     ┆ f64  ┆ f64   ┆   ┆ d            ┆ ---          ┆ ---          ┆ ---         │
│          ┆         ┆      ┆       ┆   ┆ ---          ┆ f64          ┆ f64          ┆ f64         │
│          ┆         ┆      ┆       ┆   ┆ f64          ┆              ┆              ┆             │
╞══════════╪═════════╪══════╪═══════╪═══╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 0.630957 ┆ 0.0     ┆ 0.05 ┆ 0.001 ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 7.943282 ┆ 0.2     ┆ 0.05 ┆ 0.001 ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 100.0    ┆ 0.1     ┆ 0.05 ┆ 0.001 ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 7.943282 ┆ 0.3     ┆ 0.05 ┆ 0.001 ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 100.0    ┆ 0.3     ┆ 0.05 ┆ 0.001 ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ …        ┆ …       ┆ …    ┆ …     ┆ … ┆ …            ┆ …            ┆ …            ┆ …           │
│ 0.630957 ┆ 0.3     ┆ 0.05 ┆ 0.001 ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 0.630957 ┆ 0.1     ┆ 0.05 ┆ 0.001 ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 100.0    ┆ 0.2     ┆ 0.05 ┆ 0.001 ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 7.943282 ┆ 0.0     ┆ 0.05 ┆ 0.001 ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
│ 7.943282 ┆ 0.1     ┆ 0.05 ┆ 0.001 ┆ … ┆ null         ┆ null         ┆ null         ┆ null        │
└──────────┴─────────┴──────┴───────┴───┴──────────────┴──────────────┴──────────────┴─────────────┘