In [22]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [23]:
import numpy as np
from sweep.experiment import Experiment, ExperimentType
from model.data import DataModel, KFeaturesDefinition, k_features_factory
from erm.problems.problems import ProblemType
import subprocess


Define a datamodel

In [ ]:
d = 100
vanilla_gaussian_diagonal = [(1, d)]
x_diagonal = KFeaturesDefinition(diagonal=vanilla_gaussian_diagonal)
θ_diagonal = KFeaturesDefinition(diagonal=vanilla_gaussian_diagonal)
ω_diagonal = KFeaturesDefinition(diagonal=vanilla_gaussian_diagonal)
δ_diagonal = KFeaturesDefinition(diagonal=vanilla_gaussian_diagonal)
ν_diagonal = KFeaturesDefinition(diagonal=vanilla_gaussian_diagonal)

k_features_kwargs = {
    "x_diagonal": x_diagonal,
    "θ_diagonal": θ_diagonal,
    "ω_diagonal": ω_diagonal,
    "δ_diagonal": δ_diagonal,
    "ν_diagonal": ν_diagonal,
}

data_model = DataModel(
    d,
    normalize_matrices=False,
    data_model_factory=k_features_factory,
    factory_kwargs=k_features_kwargs,
    name="vanilla-gaussian"
)

Define an experiment

In [29]:
experiment = Experiment(
    state_evolution_repetitions=1,
    erm_repetitions=1,
    alphas=np.linspace(0.01,10,5),
    epsilons=np.array([0, 0.1]),
    lambdas=np.array([0.1]),
    taus=np.array([0.1]),
    d=d,
    experiment_type=ExperimentType.Sweep,
    data_model = data_model,
    test_against_epsilons=np.array([0,0.1]),
    erm_problem_type=ProblemType.Logistic,
    gamma_fair_error=0.01,
    name="vanilla-gaussian"
)
experiment_json = experiment.to_json()

In [30]:
with open("experiment.json", "w") as f:
    f.write(experiment_json)

In [27]:
command = ["pwd"]
subprocess.run(command)

/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS


CompletedProcess(args=['pwd'], returncode=0)

In [28]:
venv_python = ".venv/bin/python"
command = ["mpiexec", "-n", "5", venv_python, "sweep/run_sweep.py", "--json", experiment_json, "--log-level", "INFO"]
subprocess.run(command)

INFO:root:The MPI comm size is 5
INFO:root:This process has rank 0
INFO:root:Starting Master for experiment vanilla-gaussian
INFO:root:Starting Experiment vanilla-gaussian
INFO:root:The MPI comm size is 5
INFO:root:This process has rank 1
INFO:root:The MPI comm size is 5
INFO:root:The MPI comm size is 5
INFO:root:This process has rank 3
INFO:root:The MPI comm size is 5
INFO:root:This process has rank 2
INFO:root:This process has rank 4
  0%|          | 0/20 [00:00<?, ?it/s]INFO:root:Starting all processes
INFO:root:Sending task 0 to 1
INFO:root:Sending task 1 to 2
INFO:root:Sending task 2 to 3
INFO:root:Sending task 3 to 4
INFO:root:All processes started - receiving results and sending new tasks
INFO:root:Received the 0th task
INFO:root:Starting task 1
INFO:root:Initializing data model
INFO:root:Starting task 2
INFO:root:Initializing data model
INFO:root:Starting task 3
INFO:root:Initializing data model
INFO:root:Starting task 4
INFO:root:Initializing data model


2025-02-16 21:30:46,741 - Rank 0 - INFO - The MPI comm size is 5
2025-02-16 21:30:46,741 - Rank 0 - INFO - This process has rank 0
2025-02-16 21:30:46,741 - Rank 0 - INFO - Starting Master for experiment vanilla-gaussian
2025-02-16 21:30:46,741 - Rank 0 - INFO - Starting Experiment vanilla-gaussian
2025-02-16 21:30:46,749 - Rank 0 - INFO - Starting all processes
2025-02-16 21:30:46,749 - Rank 0 - INFO - Sending task 0 to 1
2025-02-16 21:30:46,749 - Rank 0 - INFO - Sending task 1 to 2
2025-02-16 21:30:46,749 - Rank 0 - INFO - Sending task 2 to 3
2025-02-16 21:30:46,750 - Rank 0 - INFO - Sending task 3 to 4
2025-02-16 21:30:46,750 - Rank 0 - INFO - All processes started - receiving results and sending new tasks
2025-02-16 21:30:46,750 - Rank 0 - INFO - Received the 0th task


INFO:root:d: 100
INFO:root:normalize_matrices: False
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_δ: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ν: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_x value counts: (array([0., 1.]), array([9900,  100]))
INFO:root:Σ_ω value counts: (array([

2025-02-16 21:30:48,591 - Rank 0 - INFO - Received task 2 from 2
2025-02-16 21:30:48,600 - Rank 0 - INFO - Saved Task(id=2, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=0.0, epsilon=0.1, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x11ffbc350>)
2025-02-16 21:30:48,601 - Rank 0 - INFO - Received the 1th task
2025-02-16 21:30:48,624 - Rank 0 - INFO - Received task 1 from 1
2025-02-16 21:30:48,624 - Rank 0 - INFO - Saved Task(id=1, task_type=<Task

INFO:root:Finished State Evolution Task(id=4, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=2.5, epsilon=0.1, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=None)
INFO:root:Received task 4 from 4
INFO:root:Saved Task(id=4, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=2.5, epsilon=0.1, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(di

2025-02-16 21:30:49,889 - Rank 0 - INFO - Received task 5 from 2
2025-02-16 21:30:49,895 - Rank 0 - INFO - Saved Task(id=5, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=5.0, epsilon=0.0, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x11ffb7ed0>)
2025-02-16 21:30:49,895 - Rank 0 - INFO - Received the 5th task
2025-02-16 21:30:50,023 - Rank 0 - INFO - Received task 6 from 1
2025-02-16 21:30:50,023 - Rank 0 - INFO - Saved Task(id=6, task_type=<Task

INFO:root:Finished State Evolution Task(id=7, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.5, epsilon=0.0, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=None)
INFO:root:Received task 7 from 3
INFO:root:Saved Task(id=7, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.5, epsilon=0.0, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(di

2025-02-16 21:30:50,087 - Rank 0 - INFO - Saved Task(id=7, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.5, epsilon=0.0, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x11ffc5c10>)
2025-02-16 21:30:50,099 - Rank 0 - INFO - Received the 7th task


INFO:root:Finished State Evolution Task(id=8, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.5, epsilon=0.1, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=None)
INFO:root:Received task 8 from 4
INFO:root:Saved Task(id=8, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.5, epsilon=0.1, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(di

2025-02-16 21:30:50,302 - Rank 0 - INFO - Received task 8 from 4
2025-02-16 21:30:50,318 - Rank 0 - INFO - Saved Task(id=8, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=7.5, epsilon=0.1, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x11ffc6a10>)
2025-02-16 21:30:50,334 - Rank 0 - INFO - Received the 8th task


INFO:root:d: 100
INFO:root:normalize_matrices: False
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_δ: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ν: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_x value counts: (array([0., 1.]), array([9900,  100]))
INFO:root:Σ_ω value counts: (array([

2025-02-16 21:30:51,689 - Rank 0 - INFO - Received task 9 from 2
2025-02-16 21:30:51,701 - Rank 0 - INFO - Saved Task(id=9, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=10.0, epsilon=0.0, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x11ffc7850>)
2025-02-16 21:30:51,701 - Rank 0 - INFO - Received the 9th task


INFO:root:Finished State Evolution Task(id=10, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=10.0, epsilon=0.1, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=None)
INFO:root:Received task 10 from 1
INFO:root:Saved Task(id=10, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=10.0, epsilon=0.1, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefiniti

2025-02-16 21:30:51,935 - Rank 0 - INFO - Received task 10 from 1
2025-02-16 21:30:51,935 - Rank 0 - INFO - Saved Task(id=10, task_type=<TaskType.SE: 1>, erm_problem_type=None, alpha=10.0, epsilon=0.1, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=<sweep.results.state_evolution.SEResult object at 0x11ffd8690>)
2025-02-16 21:30:51,935 - Rank 0 - INFO - Received the 10th task


ERROR:root:Found array with 0 sample(s) (shape=(0, 100)) while a minimum of 1 is required.
Traceback (most recent call last):
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/helpers.py", line 77, in process_task
    task.result = run_erm(task, data_model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/helpers.py", line 30, in run_erm
    weights_erm, values = start_optimization(task, data_model, data)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/erm/optimize.py", line 14, in start_optimization
    w_gd, values = optimize(
                   ^^^^^^^^^
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/erm/optimize.py", line 81, in optimize
    w0, X, target, lam, epsilon = preprocessing(coef, X, y, lam, epsilon, problem_type)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2025-02-16 21:30:52,627 - Rank 0 - INFO - Received task 11 from 3
2025-02-16 21:30:52,627 - Rank 0 - ERROR - Error Task(id=11, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.Logistic: 0>, alpha=0.0, epsilon=0.0, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=ValueError('Found array with 0 sample(s) (shape=(0, 100)) while a minimum of 1 is required.'))
2025-02-16 21:30:52,627 - Rank 0 - ERROR - Found array with 0 sample(s) (shape=(0, 100)) while a minimum of 1 is required.
2025-02-16 21:30:52,627 

ERROR:root:Found array with 0 sample(s) (shape=(0, 100)) while a minimum of 1 is required.
Traceback (most recent call last):
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/helpers.py", line 77, in process_task
    task.result = run_erm(task, data_model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/helpers.py", line 30, in run_erm
    weights_erm, values = start_optimization(task, data_model, data)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/erm/optimize.py", line 14, in start_optimization
    w_gd, values = optimize(
                   ^^^^^^^^^
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/erm/optimize.py", line 81, in optimize
    w0, X, target, lam, epsilon = preprocessing(coef, X, y, lam, epsilon, problem_type)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2025-02-16 21:30:57,674 - Rank 0 - INFO - Received task 13 from 2
2025-02-16 21:30:57,675 - Rank 0 - ERROR - Error Task(id=13, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.Logistic: 0>, alpha=2.5, epsilon=0.0, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=AttributeError("'DataModel' object has no attribute 'theta'"))
2025-02-16 21:30:57,675 - Rank 0 - ERROR - 'DataModel' object has no attribute 'theta'
2025-02-16 21:30:57,675 - Rank 0 - INFO - Received the 13th task
2025-02-16 21:30:57,779 - R

ERROR:root:'DataModel' object has no attribute 'theta'
Traceback (most recent call last):
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/helpers.py", line 77, in process_task
    task.result = run_erm(task, data_model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/helpers.py", line 32, in run_erm
    erm_result = ERMResult(task, data_model, data, weights_erm, values)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/results/erm.py", line 34, in __init__
    self.rho: float = data_model.theta.dot(data_model.Sigma_x @ data_model.theta) / task.d
                      ^^^^^^^^^^^^^^^^
AttributeError: 'DataModel' object has no attribute 'theta'
INFO:root:Received task 16 from 4
ERROR:root:Error Task(id=16, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.Logistic: 0>, alpha=5.0, epsilon=0.1, tes

2025-02-16 21:30:58,328 - Rank 0 - INFO - Received task 16 from 4
2025-02-16 21:30:58,338 - Rank 0 - ERROR - Error Task(id=16, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.Logistic: 0>, alpha=5.0, epsilon=0.1, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=AttributeError("'DataModel' object has no attribute 'theta'"))
2025-02-16 21:30:58,338 - Rank 0 - ERROR - 'DataModel' object has no attribute 'theta'
2025-02-16 21:30:58,346 - Rank 0 - INFO - Received the 15th task


ERROR:root:'DataModel' object has no attribute 'theta'
Traceback (most recent call last):
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/helpers.py", line 77, in process_task
    task.result = run_erm(task, data_model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/helpers.py", line 32, in run_erm
    erm_result = ERMResult(task, data_model, data, weights_erm, values)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/results/erm.py", line 34, in __init__
    self.rho: float = data_model.theta.dot(data_model.Sigma_x @ data_model.theta) / task.d
                      ^^^^^^^^^^^^^^^^
AttributeError: 'DataModel' object has no attribute 'theta'
INFO:root:Received task 15 from 3
ERROR:root:Error Task(id=15, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.Logistic: 0>, alpha=5.0, epsilon=0.0, tes

2025-02-16 21:30:58,715 - Rank 0 - INFO - Received task 15 from 3
2025-02-16 21:30:58,753 - Rank 0 - ERROR - Error Task(id=15, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.Logistic: 0>, alpha=5.0, epsilon=0.0, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=AttributeError("'DataModel' object has no attribute 'theta'"))
2025-02-16 21:30:58,754 - Rank 0 - ERROR - 'DataModel' object has no attribute 'theta'
2025-02-16 21:30:58,754 - Rank 0 - INFO - Received the 16th task


INFO:root:d: 100
INFO:root:normalize_matrices: False
INFO:root:Ratio of first to last eigenvalue of Σ_x: 1.0
INFO:root:Norm Σ_x: 100.0
INFO:root:Norm Σ_ω: 100.0
INFO:root:Norm Σ_δ: 100.0
INFO:root:Norm Σ_ν: 100.0
INFO:root:Σ_x: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ω: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_δ: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_ν: [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
INFO:root:Σ_x value counts: (array([0., 1.]), array([9900,  100]))
INFO:root:Σ_ω value counts: (array([

2025-02-16 21:31:03,737 - Rank 0 - INFO - Received task 18 from 1
2025-02-16 21:31:03,737 - Rank 0 - ERROR - Error Task(id=18, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.Logistic: 0>, alpha=7.5, epsilon=0.1, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=AttributeError("'DataModel' object has no attribute 'theta'"))
2025-02-16 21:31:03,737 - Rank 0 - ERROR - 'DataModel' object has no attribute 'theta'
2025-02-16 21:31:03,737 - Rank 0 - INFO - Received the 17th task
2025-02-16 21:31:03,759 - R

ERROR:root:'DataModel' object has no attribute 'theta'
Traceback (most recent call last):
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/helpers.py", line 77, in process_task
    task.result = run_erm(task, data_model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/helpers.py", line 32, in run_erm
    erm_result = ERMResult(task, data_model, data, weights_erm, values)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/results/erm.py", line 34, in __init__
    self.rho: float = data_model.theta.dot(data_model.Sigma_x @ data_model.theta) / task.d
                      ^^^^^^^^^^^^^^^^
AttributeError: 'DataModel' object has no attribute 'theta'
INFO:root:Received task 19 from 4
ERROR:root:Error Task(id=19, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.Logistic: 0>, alpha=10.0, epsilon=0.0, te

2025-02-16 21:31:04,047 - Rank 0 - INFO - Received task 19 from 4
2025-02-16 21:31:04,048 - Rank 0 - ERROR - Error Task(id=19, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.Logistic: 0>, alpha=10.0, epsilon=0.0, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=AttributeError("'DataModel' object has no attribute 'theta'"))
2025-02-16 21:31:04,048 - Rank 0 - ERROR - 'DataModel' object has no attribute 'theta'
2025-02-16 21:31:04,048 - Rank 0 - INFO - Received the 19th task


ERROR:root:'DataModel' object has no attribute 'theta'
Traceback (most recent call last):
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/helpers.py", line 77, in process_task
    task.result = run_erm(task, data_model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/helpers.py", line 32, in run_erm
    erm_result = ERMResult(task, data_model, data, weights_erm, values)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kasimirtanner/Documents/LocalCode/Code_PDM/AISTATS/sweep/results/erm.py", line 34, in __init__
    self.rho: float = data_model.theta.dot(data_model.Sigma_x @ data_model.theta) / task.d
                      ^^^^^^^^^^^^^^^^
AttributeError: 'DataModel' object has no attribute 'theta'
INFO:root:Received task 20 from 3
ERROR:root:Error Task(id=20, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.Logistic: 0>, alpha=10.0, epsilon=0.1, te

2025-02-16 21:31:04,287 - Rank 0 - INFO - Received task 20 from 3
2025-02-16 21:31:04,287 - Rank 0 - ERROR - Error Task(id=20, task_type=<TaskType.ERM: 0>, erm_problem_type=<ProblemType.Logistic: 0>, alpha=10.0, epsilon=0.1, test_against_epsilons=[0.0, 0.1], lam=0.1, tau=0.1, d=100, data_model=DataModel(d=100, normalize_matrices=False, data_model_factory=k_features_factory, factory_kwargs={'x_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'θ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ω_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'δ_diagonal': KFeaturesDefinition(diagonal=[[1, 100]]), 'ν_diagonal': KFeaturesDefinition(diagonal=[[1, 100]])}, name='', description='', gamma=1), values={}, gamma_fair_error=0.01, gamma=1, result=AttributeError("'DataModel' object has no attribute 'theta'"))
2025-02-16 21:31:04,287 - Rank 0 - ERROR - 'DataModel' object has no attribute 'theta'
2025-02-16 21:31:04,287 - Rank 0 - INFO - All tasks sent and received
[mpiexec@MacBook-Pro-

KeyboardInterrupt: 